### PR TITLE
Slevomat CS updated to 6.0.0

### PR DESCRIPTION
**Pull request by kukulich**
I'm not sure if native type hints for properties should be disabled here.

### CODE REVIEW

**Comment by adaamz** [comment]
fixes #60

**Comment by VasekPurchart** [comment]
Hi, thanks for the PR (looks great!). I just wanted to try it before merging and update the commit message to match the project style, but it looks like pushes are disabled for this PR? Could you please allow them (or change the commit msg to not be in the past/passive tense?). Thanks :)

**Comment by kukulich** [comment]
@VasekPurchart Forcepushed.

**Comment by kukulich** [comment]
No change: https://github.com/slevomat/coding-standard/commits/master/SlevomatCodingStandard/Sniffs/Commenting/RequireOneLinePropertyDocCommentSniff.php

It always worked for any property phpdoc.

So it's not related to this update.

**Comment by VasekPurchart** [comment]
My guess was that some of the helpers might have changed the behavior , for example https://github.com/slevomat/coding-standard/commits/master/SlevomatCodingStandard/Helpers/DocCommentHelper.php ?

The only changes which were changed in the project I used for testing were:

* Slevomat CS: 5.0.4 -> 6.0.3
* PHPCS: 3.5.2 -> 3.5.3

So it is possible that this is caused by a change in PHPCS (although probably less likely), but since 3.5.3 is force by 6.x it does not matter anyway.

---

> It always worked for any property phpdoc.

My bad I kind of overlooked that there is property in the title :) But there is definitely a bug, which threw me off before.

See https://github.com/consistence/coding-standard/commit/485efa0653408adfe298d0a8e47c5d8e119065c4 + https://travis-ci.org/consistence/coding-standard/jobs/626363642#L305-L308 - the error is attributed to the line where a multiline (but with just one annotation) PHPDoc is starting, but which is rather a class PHPDoc. While the rest of the file is ok-ish - the missing PHPDoc property should be a different issue. The combination of these two seems to be the trigger.

So I think the sniff should stay, but there is a regression, which can be fixed in a patch release, so we do not need to solve it in this release.

Do you want me to create a separate issue or is the above reproducer enough?

**Comment by kukulich** [comment]
https://github.com/slevomat/coding-standard/releases/tag/6.0.4

**Comment by VasekPurchart** [comment]
Thanks again :)

**Comment by kukulich** [comment]
You're welcome :)

**Comment by VasekPurchart** [comment]
Backported to 3.x and released as [3.10](https://github.com/consistence/coding-standard/releases/tag/3.10) .

**Pull request merged**
