### PR TITLE
Fix PHP version constraint to allow PHP 7

### PR DESCRIPTION
**Pull request by Majkl578**

### CODE REVIEW

**Comment by VasekPurchart** [comment]
As PHP 7 is not supported yet (because it is not released yet) and I have no verification (I didn't have enough (any) code to test on) that everything works as intended in PHP 7 it is correct that the version provided checks that there are no BC breaks (as far as semantic versioning ensures that).

Btw your PR suggest supporting only PHP 7+, which I believe is by accident.

**Comment by Majkl578** [comment]
`>=7.0` was a typo, sorry, should've been `>=5.5`, fixed.

> As PHP 7 is not supported yet (because it is not released yet)

It's RC already and we use it already (not in production of course).


---
Reason for this is simple: I wanted to use your Doctrine DateTimeImmutable bundle and when I wanted to install deps & run the tests, it failed also because of this library's dependency.
But feel free to do whatever you want here, I just sent a PR for this one as well as for the two libraries. I am really interested only in making the bundle run on PHP 7. :)

**Comment by VasekPurchart** [comment]
It might be RC, but there are still a lot unsolved issues, for example there is no Xdebug for PHP 7 in Travis (https://travis-ci.org/consistence/coding-standard/jobs/76471861#L216) which means that there is no way for me to check tests reliably.

That's why I've setup all my repositories that PHP 7 is tested, but only with allow failures, which I  believe corresponds to the fact that in Composer it is unsupported by version constraint. Which is fine, because Composer allows you use them anyway with `--ignore-platform-reqs` ([this is the way my Travis is set up](https://github.com/consistence/coding-standard/blob/master/.travis.yml#L25)).

So shouldn't be the same be applied generally if you are using something that might not be supported yet? Because I don't believe that all the libraries which have set dependencies with `>=` are really supporting the new version. For example in Nette (or Symfony) there had to be done quite some work to actually support the version, although the version was "supported" before (which meant it was not working or not working properly).

---

Thanks for interest in the libraries, could you please test (at least the bundle and types) with your codebase? (I have currently no real project runnable on PHP 7) and tell me if you find anything?

I have now found that it might be possible to [install Xdebug with PHP 7 on Travis](http://docs.travis-ci.com/user/languages/php/#PHP-7), I will try that.

**Comment by Majkl578** [comment]
> there are still a lot unsolved issues

Mind to be specific? Xdebug is not part of PHP.

Also, afaik Xdebug is used only for coverage, and coverage is not part of unit tests themselves, it's only informative based on the unit test output, isn't it?
Either way, Xdebug is not compatible with PHP 7 and [it will take months to become so](http://bugs.xdebug.org/view.php?id=1109#c3152), not even sure it will be in time when 7.0.0 is out.

If we are strictly speaking, your `~5.5` constraint is too broad anyway, what if there was 5.7 instead of 7.0 (as originally proposed)? You would get breakage. If you want to be paranoid, you should specify exact versions or ranges, e.g. `>=5.5.0,<5.7.0`.

Actually you are the only vendor I have ever had problems with regarding PHP 5/7 interoperability in composer. Any project like Symfony, Doctrine, Nette etc. use `>=`.
If anyone is using unstable versions, here PHP 7.0 beta/RC, they should bear in mind that the library might not work. Paranoia is not an ideal solution.

**Comment by VasekPurchart** [comment]
> Mind to be specific? Xdebug is not part of PHP.

I know that it is not part of PHP, but it is an important part of the ecosystem (like itself Travis etc.) if you can't rely on the tools in the ecosystem you can't guarantee the functionality. And code coverage is integral part of tests, because otherwise you don't know what is tested and what is not. I believe I have set Coveralls to check PRs that should fail if they contain code which is not covered by tests.

>  Either way, Xdebug is not compatible with PHP 7 and it will take months to become so, not even sure it will be in time when 7.0.0 is out.

Thanks for the link, I didn't know about this, but they say they are planning to do so, so lets hope :)

> If we are strictly speaking, your ~5.5 constraint is too broad anyway, what if there was 5.7 instead of 7.0 (as originally proposed)? You would get breakage.

Well if there was 5.7 I don't think they would want to introduce so much BC breaks (and in that case everything would be ok). And of course there could be BC breaks, but again this can happen with any package, not only platform requirements. If they don't adhere to semantic versioning (at least to some degree), then what is the point in listing them in requirements?

The same goes with libraries - if you list a dependency on Nette ~2.3 and Nette 2.4 contains BC breaks, it's irritating because it breaks. If 3.0 is released with BC breaks then you have to update you dependency (even if it would be completely fine), but that is not a reason to put dependency on Nette >= 2.3, is it?

Similar problem is with the lower threshold - the code might work in PHP 5.4, but since there is no guarantee it is not listed as supported. 

> If anyone is using unstable versions, here PHP 7.0 beta/RC, they should bear in mind that the library might not work

Well I think that is what I mean, if you use `--ignore-platform-reqs` you are saying I am using something which might not be suppoted and I know about the drawbacks.

---

But lets be constructive - could you please try to test the libraries with your codebase? Since tests provide only assurance that it works in cases which are written in tests, that does not mean, that there are no other problems.

**Comment by VasekPurchart** [comment]
Btw update about Xdebug progress: https://twitter.com/xdebug/status/635044068918169600

**Comment by VasekPurchart** [comment]
https://twitter.com/Ocramius/status/658225000546238464 :)

**Comment by mhujer** [comment]
@VasekPurchart What about this one? I was about to create a similar PR for https://github.com/VasekPurchart/Tracy-Blue-Screen-Bundle (which cannot be installed when using PHP 7 from console), but fixing it there does not help as it depends on this one...

**Comment by Vrtak-CZ** [comment]
PHP 7.0.0 should be release today and [Xdebug 2.4.0RC1 is released](https://twitter.com/xdebug/status/668055963258212352) few days ago. I think it's time to merge support for PHP7 to master.

**Comment by hrach** [comment]
@Vrtak-CZ no, today is scheduled RC8. RTM on the 3rd of Dec.

**Comment by Majkl578** [comment]
That doesn't mattter, PHP 7 support should've been added already when RC was released...

**Comment by hrach** [comment]
Nobody claims it matters.

**Comment by VasekPurchart** [comment]
@Majkl578 as I wrote [3 months ago](https://github.com/consistence/coding-standard/pull/3#issuecomment-133056977) - I wanted to see, if everything works in real-world projects and asked, if you could give this confirmation. If you did, this would have been probably closed long ago. I have only received confirmations from real-world usage this week...

**Comment by Vrtak-CZ** [comment]
Tested on 3 @shipito project and all active @nella projects.

**Comment by VasekPurchart** [comment]
@Vrtak-CZ thanks a lot :+1: , btw @slevomat works as well

**Comment by VasekPurchart** [comment]
Closed with 2e588a3 and released with `0.8`.

**Pull request closed without merging**
