### PR TITLE
Remove composer.lock

### PR DESCRIPTION
**Pull request by Majkl578**

### CODE REVIEW

**Comment by VasekPurchart** [comment]
Since there is no description provided I don't know if I should close this PR immediately or if you are going to provide one? The lock is not committed by accident, so do you have a particular problem which it causes?

**Comment by Majkl578** [comment]
I provided a comment in the first PR of this kind sent to https://github.com/VasekPurchart/Doctrine-Date-Time-Immutable-Types/pull/2, hoped you will read it first. :)
Anyway, I don't use/know this tool, but it looks like a library and typically libraries do not version composer.lock, only composer.json. Feel free to close it if you want to diverge.

**Comment by VasekPurchart** [comment]
> hoped you will read it first

Sorry, missed that one :)

There are only a few edge cases when committing composer.lock actually causes a problem. (Travis is not using it in my projects). And having a committed composer.lock actually eases using branches a lot - dependencies do not need to be recomputed with every switch so I choose to commit it (contrary to the popular opinion) until I see a particular problem :).

**Comment by fprochazka** [comment]
It's better not to commit it in libs, because then you have easier testing of min and max installable dependencies. But for the consumer of the library, it really is irellevant.

**Comment by VasekPurchart** [comment]
@fprochazka we have already discussed this, but I don't see the benefit in

> because then you have easier testing of min and max installable dependencies

The only difference is that you call update instead of install (which essentially calls update when lock is missing). So I don't see the advantage in this point (see this repo's [travis.yml](https://github.com/consistence/coding-standard/blob/master/.travis.yml#L25) - did I miss anything?).

The only practical disadvantage I see in lock, which I didn't realize when I was deciding whether to commit it, is that it impacts the history quite a lot and therefore skews the statistics about the repository itself, but I don't know yet if this outweighs the anoyance of 

1) calling update all the time (really time consuming, especially when working with larger frameworks/libs such as Symfony)

2) probability of forgetting to update and therefore running with different dependencies than you think (because [AFAIK there is no reliable way now, to stop Composer on json/lock mismatch](https://github.com/composer/composer/issues/2783)), which can lead to really WTF situations and wasted time (especially when you work with branches, rebase etc. a lot), which is why I started to commit it in the first place - when the code was not public yet.

**Comment by VasekPurchart** [comment]
[Now there is a way to check composer.json/lock mismatch](https://github.com/composer/composer/issues/2783#issuecomment-139825286), so I removed the composer.lock in cec9b38.

**Pull request closed without merging**
